// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Entity implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject entityMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Entity";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Validation("Validation"),
		AlertStyle("AlertStyle"),
		Entity_Entity_2("MyFirstModule.Entity_Entity_2");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Entity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Entity(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject entityMendixObject)
	{
		if (entityMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, entityMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.entityMendixObject = entityMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.Entity initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Entity(context, mendixObject);
	}

	public static myfirstmodule.proxies.Entity load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Entity.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.Entity> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstmodule.proxies.Entity.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Validation
	 */
	public final java.lang.String getValidation()
	{
		return getValidation(getContext());
	}

	/**
	 * @param context
	 * @return value of Validation
	 */
	public final java.lang.String getValidation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Validation.toString());
	}

	/**
	 * Set value of Validation
	 * @param validation
	 */
	public final void setValidation(java.lang.String validation)
	{
		setValidation(getContext(), validation);
	}

	/**
	 * Set value of Validation
	 * @param context
	 * @param validation
	 */
	public final void setValidation(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String validation)
	{
		getMendixObject().setValue(context, MemberNames.Validation.toString(), validation);
	}

	/**
	 * @return value of AlertStyle
	 */
	public final java.lang.String getAlertStyle()
	{
		return getAlertStyle(getContext());
	}

	/**
	 * @param context
	 * @return value of AlertStyle
	 */
	public final java.lang.String getAlertStyle(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AlertStyle.toString());
	}

	/**
	 * Set value of AlertStyle
	 * @param alertstyle
	 */
	public final void setAlertStyle(java.lang.String alertstyle)
	{
		setAlertStyle(getContext(), alertstyle);
	}

	/**
	 * Set value of AlertStyle
	 * @param context
	 * @param alertstyle
	 */
	public final void setAlertStyle(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String alertstyle)
	{
		getMendixObject().setValue(context, MemberNames.AlertStyle.toString(), alertstyle);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Entity_Entity_2
	 */
	public final myfirstmodule.proxies.Entity_2 getEntity_Entity_2() throws com.mendix.core.CoreException
	{
		return getEntity_Entity_2(getContext());
	}

	/**
	 * @param context
	 * @return value of Entity_Entity_2
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.Entity_2 getEntity_Entity_2(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Entity_2 result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Entity_Entity_2.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.Entity_2.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Entity_Entity_2
	 * @param entity_entity_2
	 */
	public final void setEntity_Entity_2(myfirstmodule.proxies.Entity_2 entity_entity_2)
	{
		setEntity_Entity_2(getContext(), entity_entity_2);
	}

	/**
	 * Set value of Entity_Entity_2
	 * @param context
	 * @param entity_entity_2
	 */
	public final void setEntity_Entity_2(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Entity_2 entity_entity_2)
	{
		if (entity_entity_2 == null) {
			getMendixObject().setValue(context, MemberNames.Entity_Entity_2.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Entity_Entity_2.toString(), entity_entity_2.getMendixObject().getId());
		}
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return entityMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Entity that = (myfirstmodule.proxies.Entity) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
