// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the MyFirstModule module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Entity_RefreshBuilder(
		myfirstmodule.proxies.Entity _entity
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.ACT_Entity_Refresh");
		builder = builder.withParam("Entity", _entity);
		return builder;
	}

	public static void aCT_Entity_Refresh(
		IContext context,
		myfirstmodule.proxies.Entity _entity
	)
	{
		aCT_Entity_RefreshBuilder(
				_entity
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Entity_TriggerValidationBuilder(
		myfirstmodule.proxies.Entity _entity
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.ACT_Entity_TriggerValidation");
		builder = builder.withParam("Entity", _entity);
		return builder;
	}

	public static void aCT_Entity_TriggerValidation(
		IContext context,
		myfirstmodule.proxies.Entity _entity
	)
	{
		aCT_Entity_TriggerValidationBuilder(
				_entity
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Entity_TriggerValidationAssociationBuilder(
		myfirstmodule.proxies.Entity _entity
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.ACT_Entity_TriggerValidationAssociation");
		builder = builder.withParam("Entity", _entity);
		return builder;
	}

	public static void aCT_Entity_TriggerValidationAssociation(
		IContext context,
		myfirstmodule.proxies.Entity _entity
	)
	{
		aCT_Entity_TriggerValidationAssociationBuilder(
				_entity
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Entity_TriggerValidationAttributeOverAssociationBuilder(
		myfirstmodule.proxies.Entity _entity
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.ACT_Entity_TriggerValidationAttributeOverAssociation");
		builder = builder.withParam("Entity", _entity);
		return builder;
	}

	public static void aCT_Entity_TriggerValidationAttributeOverAssociation(
		IContext context,
		myfirstmodule.proxies.Entity _entity
	)
	{
		aCT_Entity_TriggerValidationAttributeOverAssociationBuilder(
				_entity
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Entity_TriggerValidationBothBuilder(
		myfirstmodule.proxies.Entity _entity
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.ACT_Entity_TriggerValidationBoth");
		builder = builder.withParam("Entity", _entity);
		return builder;
	}

	public static void aCT_Entity_TriggerValidationBoth(
		IContext context,
		myfirstmodule.proxies.Entity _entity
	)
	{
		aCT_Entity_TriggerValidationBothBuilder(
				_entity
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_Entity_GetOrCreateBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.DS_Entity_GetOrCreate");
		return builder;
	}

	public static myfirstmodule.proxies.Entity dS_Entity_GetOrCreate(IContext context)
	{
		Object result = dS_Entity_GetOrCreateBuilder().execute(context);
		return result == null ? null : myfirstmodule.proxies.Entity.initialize(context, (IMendixObject) result);
	}
}
